# استفاده از نسخه پایدار نود
FROM node:20-alpine

# ۱. نصب کتابخانه‌های سیستمی (برای حل ارور libssl و سازگاری با پریزما)
RUN apk add --no-cache openssl libc6-compat


WORKDIR /app

# ۳. استراتژی ککش: اول فقط فایل‌های پکیج را کپی می‌کنیم
# تا زمانی که لیست پکیج‌ها تغییر نکند، داکر از ککش مرحله قبل استفاده می‌کند و چیزی دانلود نمی‌شود
COPY package*.json ./
COPY prisma ./prisma/

# ۴. نصب تمام وابستگی‌ها
RUN npm install --legacy-peer-deps

# ۵. حالا کل سورس‌کد را کپی می‌کنیم
# با این کار، تغییر در کدهای شما باعث دانلود مجدد پکیج‌ها نمی‌شود
COPY . .

# ۶. ساخت کلاینت پریزما با نسخه دقیق پروژه
RUN npx prisma@5.22.0 generate

# ۷. بیلد گرفتن از پروژه
RUN npm run build
# ۲. تنظیم متغیر محیطی پروداکشن برای بهینه‌سازی اجرا
ENV NODE_ENV=production

# باز کردن پورت بک‌اند
EXPOSE 4000

# ۸. اجرای برنامه
# نکته: مسیر را در package.json به dist/src/main تغییر داده باشی
CMD ["npm", "run", "start:prod"]